### ISSUE TITLE
Save Changes button doesn't work

### ISSUE THREAD

**Issue by dimayakovlev** [lokothodida/gs-front-router#10]
Test Front Router v0.4.1 with clean GS 3.3.13. I can add routes, but I can't save changes. While there are no routes, save work fine.

**Comment by dimayakovlev** [comment]
Error in console: `An invalid form control with name='callback[]' is not focusable.`

**Comment by lokothodida** [comment]
[Fix is on the current 0.4.2 branch](https://github.com/lokothodida/gs-front-router/commit/c9c277700b9cc46c9a66c689a32383a22b94240e). It was incredibly stupid of me to set the `textarea`'s `required` property without properly testing it. Sorry about that!
