### ISSUE TITLE
I can't get to work properly

### ISSUE THREAD

**Issue by dimayakovlev** [lokothodida/gs-front-router#13]
Front Router work for me only if route is `(.*)`.  If I try others routes `FrontRouterRouter::executeFront($url)` always return `false`.

**Comment by lokothodida** [comment]
* What routes are you testing?
* What are the actions for each route?
* How are they ordered? (ideally you should have the more specific ones first)
* What GetSimple version are you using?

**Comment by dimayakovlev** [comment]
Clean installation of GS 3.3.13, no plugins except Front Router.

I'm start with your [File Listing Example](https://github.com/lokothodida/gs-front-router/wiki/File-Listing-Example). After I tried simple action for different routes like `test/(.*)`:

```php
return array(
  'title' => 'Front Router',
  'content' => 'Nothing to show',
);
```

Fancy URL's on or off - doesn't affect. Order of routes doesn't affect too.

Work only with route `(.*)`.

**Comment by lokothodida** [comment]
Copy-pasting the route into my installation (3.3.11) worked.

* Are you saying that you get a 404-error when you visit `SITEURL/test/[somepath]`, rather than showing the above title/content? Or are you saying that the other routes that you try are not working?
* What happens if you try a route with no special expressions (e.g. just `test`)?

Please run me through how to reproduce the problem (and if necessary, provide screenshots).

**Comment by dimayakovlev** [comment]
Install 3.3.11 and Front Router 0.4.2.

![Backend](https://cloud.githubusercontent.com/assets/8279974/22634709/d834929e-ec3d-11e6-8718-65ade57f2e5f.png)

![Frontend](https://cloud.githubusercontent.com/assets/8279974/22634711/e1abc9be-ec3d-11e6-8a49-deb830efa75f.png)

But if Route is `(.*)` then error appears:

![Frontend error](https://cloud.githubusercontent.com/assets/8279974/22634783/aaa26ca6-ec3e-11e6-8a33-703efd5bb406.png)

**Comment by dimayakovlev** [comment]
So strange... Still got error after upgrade GS to 3.3.13 and Front Router to 0.4.3.

![2017-02-06 3](https://cloud.githubusercontent.com/assets/8279974/22635080/2d0ca538-ec41-11e6-9836-7070db0a03ec.png)
.
![2017-02-06 5](https://cloud.githubusercontent.com/assets/8279974/22635089/3d85e334-ec41-11e6-9d62-71b1131d2ce6.png)

**Comment by lokothodida** [comment]
Add a `<?php` to the top of your action.

**Comment by dimayakovlev** [comment]
Oh, I missed this. Anyway, I got 404 error on my local server, but on hosting server works as expected. So I need to find problem with my setup.

**Comment by dimayakovlev** [comment]
@lokothodida what OS, web server and PHP version do you use?

**Comment by lokothodida** [comment]
I do my development on Cloud9 IDE.

* **OS**: `Ubuntu 14.04.3 LTS`
* **PHP version**: `PHP 5.5.9-1ubuntu4.17 (cli) (built: May 19 2016 19:05:57)`
* **Web server**: `Apache/2.4.7 (Ubuntu)`

The issue for the local server may be down to [how the URL class gets the current page's URL](https://github.com/lokothodida/gs-front-router/blob/ea6b7ddb4e4cbe62246872e43fb2c1863caad586/front_router/php/url.class.php#L37). Can you tell me what `getCurrentPageURL` is returning, and what the actual current page's URL is?

**Comment by dimayakovlev** [comment]
I do tests on my local Windows machine.

Route:
```test/(.*)```

Action:
```php
<?php
return array(
  'title' => 'Front Router',
  'content' => 'Nothing to show',
);
```

URL | FrontRouterURL::getRelativePageURL() | FrontRouterRouter::executeFront($url)
--- | --- | ---
http://gs-old.localhost/ | (string) | (bool)false
http://gs-old.localhost/test/ | (string)test | (bool)false
http://gs-old.localhost/test/fake | (string)test/fake | (bool)false

**Comment by lokothodida** [comment]
That is _very_ odd. If `getRelativePageURL()` is getting the correct URL then `executeFront()` should work correctly too.

At [`findMatchedRoute()`](https://github.com/lokothodida/gs-front-router/blob/ea6b7ddb4e4cbe62246872e43fb2c1863caad586/front_router/php/router.class.php#L75), can you tell me the values of `$pattern`, `$url` and `$match` that you are getting in the `foreach` loop?

**Comment by dimayakovlev** [comment]
Same route and action as in previous test.

URL | $pattern | $url | $match
--- | --- | --- | ---
http://gs-old.localhost/ | (string)"/^\/test\/(.*)$/" | (string) | (int)0
http://gs-old.localhost/test/ | (string)"/^\/test\/(.*)$/" | (string)"test" | (int)0
http://gs-old.localhost/test/fake | (string)"/^\/test\/(.*)$/" | (string)"test/fake" | (int)0

**Comment by lokothodida** [comment]
Okay, so the route is failing because there is an extra `/` snuck in there before the route's string. `/^/test/(.*)$/` should instead be `/^test/(.*)$/`. But I'm not sure where it is coming from. Does your route have one at the start? (i.e. is it `/test/(.*)`)?

**Comment by dimayakovlev** [comment]
No, my route is `test/(.*)`. And there is no extra `/` on Linux: `"/^test\/(.*)$/"`. Problem appears on Windows.

**Comment by dimayakovlev** [comment]
@lokothodida It was my stupid mistake! I was sure about syncing remote and local copy of the `routes.json`. So I don't check settings on my local installation via admin panel. There is leading `/` in my local route. Sorry for that.

**Comment by lokothodida** [comment]
No problem, @dimayakovlev. This discussion has opened some possible changes to the plugin:

* Should `<?php` be necessary at the start of actions? Given that the user has to return an `array` of data, perhaps not. Especially considering the fact that actual `echo`ed content will not be shown until the `content`'s callback is called.
* Should `/` automatically be stripped from the beginning of routes when the data is saved?
* Should there be short-hand routes, such as `$slug`, which automatically matches page slugs `([a-z0-9-]+)`?

**Comment by dimayakovlev** [comment]
Seems I found a problem! One local installation, but different URLs.

- `http://gs-old:8080/test/tmp` - got 404 page;
- `http://gs-old.local/test/tmp` - work as expected.

Problem in URL name! In first example `$url` variable has value `gs-old/test/tmp`. So it doesn't match.

**Comment by lokothodida** [comment]
[getRelativePageURL()](https://github.com/lokothodida/gs-front-router/blob/ea6b7ddb4e4cbe62246872e43fb2c1863caad586/front_router/php/url.class.php#L24) strips off the site's URL (defined in your settings) from the full page URL, in order to match the route. Since your address is `http://gs-old.local` it doesn't strip off `http://gs-old:8080`. But I do not know how to consistently get the site's canonical URL without using the `$SITEURL` variable (because a GetSimple installation can be nested in a folder, and so the domain name alone isn't sufficient to infer the installation's base address).

*edit* I could allow users to add a selection of base URLs to match from. This would be particularly useful if they have multiple domain names.

**Comment by dimayakovlev** [comment]
I run different webserver setups alternately and change URLs in GS settings for each setup. I create new route `gs-old/test/(*.)` and it work with `http://gs-old:8080/test/tmp`.

**Comment by lokothodida** [comment]
Are you saying that `gs-old/test/(*.)` actually worked for `http://gs-old:8080/test/tmp` with `http://gs-old.local` as the site URL, or that you would like the plugin to have the option of multiple site URLs?

**Comment by dimayakovlev** [comment]
@lokothodida no!

First setup:

 - URL: http://gs-old:8080/test/tmp
- `$SITEURL`: http://gs-old:8080/
- `FrontRouterURL::getRelativePageURL()`: `gs-old/test/tmp`
- Working route: `gs-old/test/(*.)`

Second setup:

 - URL: http://gs-old.local/test/tmp
- `$SITEURL`: http://gs-old.local/
- `FrontRouterURL::getRelativePageURL()`: `test/tmp`
- Working route: `test/(*.)`

In first setup `FrontRouterURL::getRelativePageURL()` return wrong result.

**Comment by lokothodida** [comment]
On this line of [`getCurrentPageURL()`](https://github.com/lokothodida/gs-front-router/blob/ea6b7ddb4e4cbe62246872e43fb2c1863caad586/front_router/php/url.class.php#L39), does changing `SERVER_NAME` to `HTTP_HOST` do anything? I suspect that the port (`8080`) not being included in the full site URL might be causing the issue.

**Comment by dimayakovlev** [comment]
Changing `SERVER_NAME`  to `HTTP_HOST` solves problem.
