### ISSUE TITLE
Warning: It is not yet possible to assign complex types to properties in root\plugins\front_router\php\plugin.class.php on line 62

### ISSUE THREAD

**Issue by webketje** [lokothodida/gs-front-router#16]
- PHP V5.4.3
- no fancy URLs
- when? when navigating to the defined route

**Route**: files (index.php?id=files)
**Action**:
````
<?php 
   return array(
    'title' => 'hello',
    'content' => function() {
      return 'test';
    }
);
````

**Comment by lokothodida** [comment]
The `content` function is meant to print out the content. Under the hood the plugin handles output buffering for you, so you can just echo the result:

```html+php
 <?php 
   return array(
    'title'   => 'hello',
    'content' => function() {
      echo 'test';
    }
  );
```

Nevertheless, it is still unintended behaviour, so there is a bugfix for it (referenced).
